version: "3.8"
services:
    mysql:
        image: mysql
        container_name: app-mysql                
        ports:
            - "3320:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testdb
    loader:
        container_name: app-loader                
        build:
            context: ./
            dockerfile: Dockerfile
        command: python load.py
        depends_on: 
            - mysql
    app:
        container_name: app-api                
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        depends_on: 
            - mysql
            - loader